In [1]:
import itertools
import numpy as np

def build_hamming_check(m):
    """Строим проверочную матрицу для кода Хэмминга длины"""
    columns = []
    for num in range(1, 2**m):
        binary = [(num >> bit) & 1 for bit in range(m-1, -1, -1)]
        columns.append(binary)
    return np.array(columns).T % 2

def create_all_codewords(gen_matrix):
    """Генерируем все кодовые слова по порождающей матрице"""
    rows, cols = gen_matrix.shape
    words = []
    
    for info in itertools.product([0, 1], repeat=rows):
        vector = np.array(info, dtype=int)
   
        encoded = (vector @ gen_matrix) % 2
        words.append(encoded)
    
    return np.array(words, dtype=int)

def count_ones(vector):
    """Подсчитываем количество единиц в двоичном векторе"""
    return int(np.sum(vector))

def calculate_distance(vec1, vec2):
    """Вычисляем расстояние Хэмминга между двумя векторами"""
  
    return int(np.sum((vec1 + vec2) % 2))

def check_simplex_properties(parameter):
    """Проверяет, является ли дуальный код кодом Хэмминга симплексным"""
    
    H = build_hamming_check(parameter)
    dual_generator = H.copy()
    
    all_words = create_all_codewords(dual_generator)
    
    code_length = 2**parameter - 1
    dimension = parameter
    target_weight = 2**(parameter - 1)
    
    print(f"Параметр m = {parameter}")
    print(f"Ожидаемые характеристики: [{code_length}, {dimension}, {target_weight}]")
    print("\nПорождающая матрица дуального кода:")
    print(dual_generator)
    
    print("\nСписок всех кодовых слов:")
    for idx, word in enumerate(all_words):
        word_str = ''.join(map(str, word))
        ones_count = count_ones(word)
        print(f"{idx:2d}: {word_str}   вес = {ones_count}")
    
  
    non_zero = [w for w in all_words if np.any(w != 0)]
    weights_list = [count_ones(w) for w in non_zero]
    
    print("\nВеса ненулевых слов:")
    print(weights_list)
    
    weight_check = all(w == target_weight for w in weights_list)
    print(f"\nВсе ненулевые слова имеют вес {target_weight}: {weight_check}")
    
 
    distances_list = []
    distance_check = True
    
    for first in range(len(all_words)):
        for second in range(first + 1, len(all_words)):
            dist = calculate_distance(all_words[first], all_words[second])
            distances_list.append(dist)
            if dist != target_weight:
                distance_check = False
    
    print("\nРасстояния между различными парами слов:")
    print(distances_list)
    print(f"\nВсе расстояния равны {target_weight}: {distance_check}")
    
    if weight_check and distance_check:
        print("\n Результат: дуальный код к коду Хэмминга является симплексным.")
    else:
        print("\n Результат: проверка не пройдена.")


check_simplex_properties(3)

Параметр m = 3
Ожидаемые характеристики: [7, 3, 4]

Порождающая матрица дуального кода:
[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]

Список всех кодовых слов:
 0: 0000000   вес = 0
 1: 1010101   вес = 4
 2: 0110011   вес = 4
 3: 1100110   вес = 4
 4: 0001111   вес = 4
 5: 1011010   вес = 4
 6: 0111100   вес = 4
 7: 1101001   вес = 4

Веса ненулевых слов:
[4, 4, 4, 4, 4, 4, 4]

Все ненулевые слова имеют вес 4: True

Расстояния между различными парами слов:
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

Все расстояния равны 4: True

 Результат: дуальный код к коду Хэмминга является симплексным.
